name: Bundler

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pqc-single-https-reverse-proxy-ruby-openssl:
    name: PQC single HTTPS TLS reverse proxy (Ruby OpenSSL)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: bundler
    steps:
      - uses: actions/checkout@v4

      - &setup-ruby
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - uses: ./.github/actions/setup-openssl

      - name: Setup
        run: ../rubygems/script/setup.sh

      - &clone-rubygems-server
        name: Clone rubygems-server (workaround for ruby-head)
        if: matrix.ruby-version == 'head'
        run: git clone https://github.com/ruby/rubygems-server.git ~/git/ruby/rubygems-server

      - name: Run HTTP server, PQC single TLS proxy, and client
        run: |
          ../rubygems/script/run_http_server.sh &
          sleep 2
          ../rubygems/script/run_https_reverse_proxy.rb -s &
          sleep 2
          script/run_client.sh

  pqc-single-https-reverse-proxy-nginx:
    name: PQC single HTTPS TLS reverse proxy (Nginx)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: bundler
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl

      - name: Setup
        run: ../rubygems/script/setup_nginx.sh

      - *clone-rubygems-server

      - name: Run HTTP server, PQC single Nginx TLS proxy, and client
        run: |
          ../rubygems/script/run_http_server.sh &
          sleep 2
          ../rubygems/script/run_https_reverse_proxy_nginx.sh -s &
          sleep 2
          script/run_client.sh
