name: DRb

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  druby:
    name: druby
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: drb
    steps:
      - uses: actions/checkout@v4

      - &setup-ruby
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Run druby server and client
        run: |
          script/run_druby_server.rb &
          sleep 3
          script/run_druby_client.rb

  drbssl:
    name: drbssl
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: drb
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl

      # Reinstall openssl gem against custom OpenSSL >= 3.6 to some methods
      # enabled for compiling OpenSSL >= 3.6
      - &reinstall-openssl-gem
        name: Reinstall openssl gem against custom OpenSSL
        run: gem install openssl -- --with-openssl-dir=$HOME/openssl

      - name: Run drbssl server and client
        run: |
          script/run_drbssl_server.rb &
          sleep 3
          script/run_drbssl_client.rb

  drbssl-rsa:
    name: drbssl RSA
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: drb
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl
      - *reinstall-openssl-gem

      - name: Setup
        run: script/setup.sh

      - name: Run drbssl RSA server and client
        run: |
          script/run_drbssl_server_rsa.rb &
          sleep 3
          script/run_drbssl_client_rsa.rb

  drbssl-mldsa65:
    name: drbssl ML-DSA-65
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: drb
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl
      - *reinstall-openssl-gem

      - name: Setup
        run: script/setup.sh

      - name: Run drbssl ML-DSA-65 server and client
        run: |
          script/run_drbssl_server_mldsa65.rb &
          sleep 3
          script/run_drbssl_client_mldsa65.rb
