name: OpenSSL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ssl-mldsa65:
    name: ssl pre-generated ML-DSA-65
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: openssl
    steps:
      - uses: actions/checkout@v4

      - &setup-ruby
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - uses: ./.github/actions/setup-openssl

      - &reinstall-openssl-gem
        name: Reinstall openssl gem against custom OpenSSL
        run: gem install openssl -- --with-openssl-dir=$HOME/openssl

      - name: Setup
        run: script/setup.sh

      - name: Run SSL ML-DSA-65 server and client
        run: |
          script/run_ssl_server_mldsa65_pre_generated.rb &
          sleep 3
          script/run_ssl_client_mldsa65_pre_generated.rb

  ssl-mldsa65-client-cert:
    name: ssl pre-generated ML-DSA-65 with client cert
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: openssl
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl
      - *reinstall-openssl-gem

      - name: Setup
        run: script/setup.sh

      - name: Run SSL ML-DSA-65 client cert server and client
        run: |
          script/run_ssl_server_mldsa65_client_cert_pre_generated.rb &
          sleep 3
          script/run_ssl_client_mldsa65_client_cert_pre_generated.rb

  ssl-multi-cert-mldsa65-rsa:
    name: ssl pre-generated ML-DSA-65/RSA multi cert
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: openssl
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl
      - *reinstall-openssl-gem

      - name: Setup
        run: script/setup.sh

      - name: Run SSL multi cert ML-DSA-65/RSA server and client
        run: |
          script/run_ssl_server_multi_cert_mldsa65_rsa_pre_generated.rb &
          sleep 3
          script/run_ssl_client_multi_cert_mldsa65_rsa_pre_generated.rb

  ssl-multi-cert-mldsa65-rsa-client-cert:
    name: ssl pre-generated ML-DSA-65/RSA multi cert with client cert
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: openssl
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl
      - *reinstall-openssl-gem

      - name: Setup
        run: script/setup.sh

      - name: Run SSL multi cert ML-DSA-65/RSA client cert server and client
        run: |
          script/run_ssl_server_multi_cert_mldsa65_rsa_client_cert_pre_generated.rb &
          sleep 3
          script/run_ssl_client_multi_cert_mldsa65_rsa_client_cert_pre_generated.rb
