name: RubyGems

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  http:
    name: HTTP server/client
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: rubygems
    steps:
      - uses: actions/checkout@v4

      - &setup-ruby
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - uses: ./.github/actions/setup-openssl

      - name: Setup
        run: script/setup.sh

      # Fix handling RDoc::Servlet rename to RDoc::RI::Servlet
      # https://github.com/rubygems/rubygems-server/pull/14
      - &clone-rubygems-server
        name: Clone rubygems-server (workaround for ruby-head)
        if: matrix.ruby-version == 'head'
        run: git clone https://github.com/ruby/rubygems-server.git ~/git/ruby/rubygems-server

      - name: Run HTTP server and client
        run: |
          script/run_http_server.sh &
          sleep 3
          script/run_http_client.sh

  https-direct:
    name: HTTPS direct (WEBrick)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: rubygems
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl

      - name: Setup
        run: script/setup.sh

      - name: Run HTTPS server and client
        run: |
          script/run_https_server.rb &
          sleep 3
          script/run_https_client.sh

  https-reverse-proxy-ruby-openssl:
    name: HTTPS TLS reverse proxy (Ruby OpenSSL)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: rubygems
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl

      - name: Setup
        run: script/setup.sh

      - *clone-rubygems-server

      - name: Run HTTP server, TLS proxy, and client
        run: |
          script/run_http_server.sh &
          sleep 2
          script/run_https_reverse_proxy.rb &
          sleep 2
          script/run_https_client.sh

  https-reverse-proxy-nginx:
    name: HTTPS TLS reverse proxy (Nginx)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: rubygems
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl

      - name: Setup
        run: script/setup_nginx.sh

      - *clone-rubygems-server

      - name: Run HTTP server, Nginx TLS proxy, and client
        run: |
          script/run_http_server.sh &
          sleep 2
          script/run_https_reverse_proxy_nginx.sh &
          sleep 2
          script/run_https_client.sh

  pqc-single-https-direct:
    name: PQC single HTTPS direct (WEBrick)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: rubygems
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl

      - name: Setup
        run: script/setup.sh

      - name: Run PQC single HTTPS server and client
        run: |
          script/run_https_server.rb -s &
          sleep 3
          script/run_https_client.sh -s

  pqc-single-https-reverse-proxy-ruby-openssl:
    name: PQC single HTTPS TLS reverse proxy (Ruby OpenSSL)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: rubygems
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl

      - name: Setup
        run: script/setup.sh

      - *clone-rubygems-server

      - name: Run HTTP server, PQC single TLS proxy, and client
        run: |
          script/run_http_server.sh &
          sleep 2
          script/run_https_reverse_proxy.rb -s &
          sleep 2
          script/run_https_client.sh -s

  pqc-single-https-reverse-proxy-nginx:
    name: PQC single HTTPS TLS reverse proxy (Nginx)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: rubygems
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl

      - name: Setup
        run: script/setup_nginx.sh

      - *clone-rubygems-server

      - name: Run HTTP server, PQC single Nginx TLS proxy, and client
        run: |
          script/run_http_server.sh &
          sleep 2
          script/run_https_reverse_proxy_nginx.sh -s &
          sleep 2
          script/run_https_client.sh -s

  pqc-dual-https-direct:
    name: PQC dual HTTPS direct (WEBrick)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: rubygems
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl

      - name: Setup
        run: script/setup.sh

      - name: Run PQC dual HTTPS server and client
        run: |
          script/run_https_server.rb -d &
          sleep 3
          script/run_https_client.sh -d

  pqc-dual-https-reverse-proxy-ruby-openssl:
    name: PQC dual HTTPS TLS reverse proxy (Ruby OpenSSL)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: rubygems
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl

      - name: Setup
        run: script/setup.sh

      - *clone-rubygems-server

      - name: Run HTTP server, PQC dual TLS proxy, and client
        run: |
          script/run_http_server.sh &
          sleep 2
          script/run_https_reverse_proxy.rb -d &
          sleep 2
          script/run_https_client.sh -d

  pqc-dual-https-reverse-proxy-nginx:
    name: PQC dual HTTPS TLS reverse proxy (Nginx)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: rubygems
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl

      - name: Setup
        run: script/setup_nginx.sh

      - *clone-rubygems-server

      - name: Run HTTP server, PQC dual Nginx TLS proxy, and client
        run: |
          script/run_http_server.sh &
          sleep 2
          script/run_https_reverse_proxy_nginx.sh -d &
          sleep 2
          script/run_https_client.sh -d

  # Test use cases with signed gems documented on the following page
  # https://guides.rubygems.org/security/
  signed-gem:
    name: Signed gem
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['4.0', 'head']
    defaults:
      run:
        working-directory: rubygems
    steps:
      - uses: actions/checkout@v4
      - *setup-ruby
      - uses: ./.github/actions/setup-openssl

      - name: Install expect
        run: sudo apt install -y expect

      - name: Run signed gem test
        run: script/test_signed_gems.sh
